### ISSUE TITLE
Additional developer power

### ISSUE THREAD

**Issue by suze27** [mplp/docassemble-mlhframework#1]
Ang met with Bryce; he's interested in 20 hours/week for 6 months starting 10/1. Ang got clearance to hire him for this work budget-wise and sole-source-wise. This may also mean we don't need additional assistance from Suffolk. Are Brett and Emily on board?

**Comment by ekressmiller** [comment]
Emily’s on board!

**Comment by suze27** [comment]
start working in september to get him access to github, servers,

**Comment by suze27** [comment]
Contract drafted and with Ann for board approval; Bryce has reviewed it and with a few small edits he is ready to sign.

**Comment by BryceStevenWilley** [comment]
And now I'm here! I have everything setup (i.e. github, servers), the only thing that I think I might eventually need access to is the LHI organization as a developer. I requested access to that today (username: brycestevenwilley), but I don't think that access is urgent, so I might close this issue for now?
