### ISSUE TITLE
ID person has attorney: 
User feedback: something
(`other_parties[0].has_attorney`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-mlhframework#112]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `person has attorney`
Details | On LHI, we allowed "I don't know" as an answer for whether the other party has a lawyer.  Was it intentional to remove that option?

If we want to leave it like this, maybe we should add some help text to explain how you would find out (look at court papers), and telling them to answer "No" if there's no lawyer mentioned on any papers and they haven't seen or heard about any lawyer.
Variable being sought | `other_parties[0].has_attorney`
Package version | `0.2`
Filename | `docassemble.FeeWaiverRequest:data/questions/fee_waiver_request.yml`

**Comment by normon66** [comment]
I was able to code an "I don't know" option into the framework, but it turned the review screen for the fee waiver into absolute hell. Decided to take Emily's suggestion, keep just the Yes/No options, and add some help text.

![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/d3ab5489-d185-4a82-8174-a722e485f51e)

**Comment by ekressmiller** [comment]
I think the merge resolves this.
