### ISSUE TITLE
Put time and materials info on MLH_intro_landing

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#116]
@normon66 I accidentally committed to Main instead of my branch for this. But could you take a look at the commit below when you have a minute and let me know if you see any issues? I left MLH_intro_time there as an option since you rightly pointed out we might want to include that info separately instead of in the welcome screen in some cases.

commit: https://github.com/mplp/docassemble-mlhframework/commit/0f3edb58013a12b3da4ed0e710401b41f654ccd2

Looks like this:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/de3a7ad9-b465-4f2d-9c95-097acaf44f3c)

**Comment by normon66** [comment]
Looks good to me!
