### ISSUE TITLE
ID court type choice: 
User feedback: something
(`court_type_selection`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-mlhframework#124]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `court type choice`
Details | Feedback on help text for the court selection page. The current link title is "What is this?" Consider changing to "How do I know?" because that is a little more specific. There is an initial paragraph defining a civil case that I think we could cut-- leaving just the names of the courts.

In the circuit definition, we should probably also add that domestic relations cases, such as divorce, child support, and custody cases are heard in that court. Personal protection cases also happen in circuit court.

I can work on a draft of this in a google doc-- linking here and will update it and send to the other MLH lawyers too. I'll add a note at the top when it is finished:

https://docs.google.com/document/d/1YxQRzXMrMuS3MIj7B2XOqUJ4GeFpN5d1M_yMV2lNOPA/edit
Variable being sought | `court_type_selection`
Package version | `0.3`
Filename | `docassemble.FeeWaiverRequest:data/questions/fee_waiver_request.yml`

**Comment by normon66** [comment]
Fixed via PR #128
