### ISSUE TITLE
ID MLH intro saving answers logged in: 
User feedback: something
(`MLH_intro_navigate_save`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-mlhframework#127]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `MLH intro saving answers logged in`
Details | "Tapping" seems werid on a computer. Consider changing from:

You can also see and edit earlier answers by tapping the “✎ Review / Edit” link.

To :
You can also see and edit earlier answers with the “✎ Review / Edit” link.
Variable being sought | `MLH_intro_navigate_save`
Package version | `0.3`
Filename | `docassemble.FeeWaiverRequest:data/questions/fee_waiver_request.yml`

**Comment by ekressmiller** [comment]
Yeah, I appreciate Kim's perspective on this, but I think from a mobile-first perspective, sticking with "tapping" here makes sense unless we get user feedback at some point that this is actively confusing people. 

As I recall, Bryce looked into trying to make it change dynamically and there wasn't a good solution for that.
