### ISSUE TITLE
ID DownloadScreen: 
User feedback: something
(`fee_waiver_request_download`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-mlhframework#132]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `DownloadScreen`
Details | The instructions sheet goes barely over one page. If you remove this line from above the header, will it all fit on one page? It appears later on the page and I don't think it needs to go in twice:

"For online instructions, visit https://michiganlegalhelp.org/node/2066"
Variable being sought | `fee_waiver_request_download`
Package version | `0.3`
Filename | `docassemble.FeeWaiverRequest:data/questions/fee_waiver_request.yml`

**Comment by normon66** [comment]
This was transferred from the Fee Waiver repo
