### ISSUE TITLE
repeated buttons on Voice RSS interface

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#15]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/efaa03a3-1626-49cb-94a7-00899ec9489b)

Since the CSS changes, the RSS Voice controls now have repeated listen and stop buttons.

**Comment by BryceStevenWilley** [comment]
I can't seem to recreate this one, on Chrome or Firefox. The Voice controls are working fine when I restart and pause.

Does it just happen when you load the page, or did you interact with the page and then it happened. It'd also help if you can look at the browser console and copy any text that's there into this issue. F12 or going to "Developer tools" in the menu should get you there, and then clicking on the "Console" tab. 
![Screenshot from 2023-10-13 11-24-48](https://github.com/mplp/docassemble-mlhframework/assets/6252212/f7d716a7-d2fd-443c-8e42-13af1f3700f7)

**Comment by ekressmiller** [comment]
I get this on the "My Interviews" page.  It happens when I go there through the menu.  I'm in Chrome.

The controls look normal when I'm inside an interview.  

Here's what I see in the console:
www.googletagmanager.com/gtag/js?id=G-C9WQEMGGSL:1     Failed to load resource: the server responded with a status of 404 ()
/interview?i=docassemble.mlhframework:data/questions/interview_list.yml#page1:1 Unchecked runtime.lastError: The message port closed before a response was received.
/interview?i=docassemble.mlhframework:data/questions/interview_list.yml#page1:1 Unchecked runtime.lastError: The message port closed before a response was received.
/interview?i=docassemble.mlhframework:data/questions/interview_list.yml#page1:1 Unchecked runtime.lastError: The message port closed before a response was received.
/interview?i=docassemble.mlhframework:data/questions/interview_list.yml#page1:1 Unchecked runtime.lastError: The message port closed before a response was received.
/interview?i=docasse…ew_list.yml#page1:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by BryceStevenWilley** [comment]
Ah, I see it now, didn't realize it was only that page. Thanks!

**Comment by ekressmiller** [comment]
Should have specified! I didn't really realize it either until you said you couldn't find it.

**Comment by BryceStevenWilley** [comment]
Okay, found the issue, it's something with AssemblyLine. When we include both `docassemble.AssemblyLine:assembly_line.yml` (which `mlh_interview_framework.yml` does) and `interview_list.yml`, the same code to adjust the RSS voice stuff runs twice, which adds all of the other widgets. I'll work on a fix now!

**Comment by BryceStevenWilley** [comment]
Just merged a fix upstream which should fix this issue when we install AssemblyLine from `main`, or wait until the 2.26.1 or 2.27.0 release.

**Comment by ekressmiller** [comment]
Awesome, thank you!
