### ISSUE TITLE
CSS notes

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#16]
I'm gonna make this issue to list all of the small things wrong with the new CSS theme that we could change. but that we should discuss more before doing so. If it's a more critical accessibility issue like a contrast issue, I'll probably make a PR to fix those sooner.

* ~The progress bar background is a really dark gray, not a huge fan of. It only seems to show up in Chrome though, not Firefox.~ when I revisited this, it looks normal! Must have been some fleeting bug in chrome for me.
  
    ![Screenshot from 2023-10-13 11-09-47](https://github.com/mplp/docassemble-mlhframework/assets/6252212/798751bb-69f4-430b-b7d9-74b919e60ffd)

* [x] A lot of the links on the page are too light, and have contrast issues (I think I addressed this in a different run through of the bootstrap theme)

    ![Screenshot from 2023-10-13 11-11-10](https://github.com/mplp/docassemble-mlhframework/assets/6252212/0ed257c1-f245-46c2-b24a-7d69792730f5)

* [x] Font size on the field labels push the text a little close to the "required" asterisk: 

  ![Screenshot from 2023-10-16 16-52-33](https://github.com/mplp/docassemble-mlhframework/assets/6252212/d870395e-e3a1-4155-96e0-ece9b6171cf2)

**Comment by normon66** [comment]
In terms of theming with mlh.org:

The 'progress bar' in the [Guide to Legal Help](https://michiganlegalhelp.org/guide-to-legal-help) has good contrast - perhaps the docassemable colors could be the same? However, the light blue bar on this doesn't have great contrast with the white background.
![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/b820c448-9790-4bd0-ac75-8b6812c227f5)

Link colors could be the same as the links at the top of mlh.org:
![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/33327c12-5955-499e-98b1-b71f8af67def)

**Comment by ekressmiller** [comment]
I wonder if it's possible to have an outline around the progress bar to help with the contrast issue?  Agree with Brett that the progress bar in the Guide and the link color on mlh.org are good places to start.  

I also agree that asterisk is a little too close to the field labels now.

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/9a556cb1-00b7-4c80-92ba-aadcd820009c)
In general, I think the fact these labels are right justified is not good for readability.

**Comment by BryceStevenWilley** [comment]
Good points. I'll see if we can give them more space and left-justify.

> Wondering if we can make longer questions appear above the radio buttons instead.

We can! You can add `label above field: True` to the field [docs here](https://docassemble.org/docs/fields.html#label%20above%20field).

I don't know why I hadn't thought of using it before, I had been stuck on trying to make that wording smaller.

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/a341dc66-d4ae-4a40-a031-3ada7e1640c3)

Text at upper right does not pass contrast check.
Seems to be set by this (ignore the values in the image below, I messed with them)
<img width="233" alt="image" src="https://github.com/mplp/docassemble-mlhframework/assets/110936328/bd4ee7ae-4e5d-44d9-8649-a82c74db4c80">

**Comment by BryceStevenWilley** [comment]
> Text at upper right does not pass contrast check.

Thanks! Some of the first pass contrast checks I use didn't detect that, curious how you found it so I can do the same!

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/b930aa7d-a782-4857-b51b-c9c13819a930)
contrast issue in description of tool on list page on Iphone.

I'm not sure if we actually want to include the description on the list page though, so maybe it doesn't matter.

**Comment by BryceStevenWilley** [comment]
Awesome! I've fixed all of these problems that I've found in this issue. If any more pop up, feel free to make a new issue for them (just so this one doesn't get unwieldy).
