### ISSUE TITLE
feedback "Exit" button destination

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#17]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/6b2a907e-9abc-463f-8e2c-605960bcde21)
 
Currently, this goes courtformsonline.   

On the dev server, where should we send people from here?  I think it makes sense to go back to the "list" page for the server, so they can easily restart the interview?  

We could tell our testers to go to the "My Inteviews" page instead if they want to resume their prior interview.  (We may not want them to resume the prior interview if there was a tricky logic bug, so we still have the variable info, but if it was just a language thing, it could be super annoying to make them restart every time they give feedback.)

**Comment by BryceStevenWilley** [comment]
I think we know what type of feedback they are giving, it's a dropdown on the previous screen, right? We can edit this screen to say "return to the interview" and link back to the session itself if it's a language thing, or "restart the interview" and back to a new session of the interview if it's a bug. 

I think the feedback page opens in a new tab; we could also open it in same tab if we wanted to make what we want them to do clearer.

**Comment by ekressmiller** [comment]
Ugh, sorry, for some reason I though it opened in the same tab just now (probably just because I already had too many Docassemble-related tabs open).  But you're right, thanks for pointing that out!

I think it's probably better to leave it so the feedback screen opens in a new tab.  Just thinking they may want to be able to see the page while they're typing their message and adding any follow-up screenshots to Github.

Maybe if it's a language thing or other suggestion, we could say something like "You can go back to the tab with your interview and continue where you left off or "restart the interview" [button]   If it's a bug, we could say "Please close the tab where you encountered the bug. To keep testing, "restart the interview" [button]
