### ISSUE TITLE
feedback not automatically creating GitHub issue in child support motion interview

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#18]
I installed the child support motion interview on the dev server. I tried to submit feedback but it did not automatically create a Github Issue (though the button to create an issue was there when I went to the Browse Feedback interview).

Not sure why that would be.  Will look into it later, or let me know if anyone has thoughts!

**Comment by normon66** [comment]
Just a little type - docassemble is missing an 's' in the repo name in code

![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/5bf81525-d32a-413d-8ae9-3c9b510beaad)

**Comment by ekressmiller** [comment]
thanks Brett!
