### ISSUE TITLE
suggest changing language from "Michigan Legal Help's [DIY tool name] tool" to "the [DIY too name] tool."

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#19]
https://github.com/mplp/docassemble-mlhframework/blob/b9e5bf9291bc9587705115eab36f46f681ea2ad6/docassemble/mlhframework/data/questions/mlh_interview_framework.yml#L132

![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/3e18b091-4cc3-4aef-bed1-16841481d360)

I think it's a bit long to include Michigan Legal Help and with the new branding and everything, I think it's clear enough that it's our tool.  What do you think @normon66 ?

**Comment by ekressmiller** [comment]
@BryceStevenWilley similar suggestion for the child support tool's intro screen.

**Comment by normon66** [comment]
Being that MLH is in the header, [currently] in the footer, and they more
than likely got to the tool *from* Michigan Legal Help, I suppose it is a
little redundant to have it in the text, as well. Good suggestion!
