### ISSUE TITLE
feedback form not generating a report in "Browse Interview Feedback"

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#21]
When I try to give feedback on this page of the child support interview
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/0feb0d7f-e669-4a69-a7d7-840ef8aafbbf)
nothing shows up in the Browse Interview Feedback interview. 

First time I've run into this.  I tried multiple times selecting both language fix and "something else to tell you"

**Comment by BryceStevenWilley** [comment]
Looks like I misspelled the repo name when writing this! Apologies! It looks like all of your feedback was saved on the server correctly, so I'll move it over to the correct github repo.

If anything weird ever happens like this again in the Feedback form, it should print enough information in the logs to find out what's happening. This time, these lines were in the `docassemble.log`:

```
docassemble: ... 2023-10-23 13:36:13 Was not able to find nor create the MLH user feedback label: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/issues/labels#create-a-label"}
docassemble: ... 2023-10-23 13:36:13 Could not create Issue "ID have_circumstances_changed:  User feedback: bug (`have_circumstances_changed`)", results {"message":"Not Found","documentation_url":"https://docs.github.com/rest/issues/issues#create-an-issue"}
docassemble: ... 2023-10-23 13:36:13 This form was not able to add an issue on the mplp/docasemble-MLHMotionRegardingChildSupport repo. Check your config.
```
