### ISSUE TITLE
Revert left-align CSS change

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#28]
It certainly messes up the alignment of required vs non-required labels. I think the better solution was mentioned in https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/issues/11, just putting the label above the field if the label is longer than 2 lines.

![Screenshot from 2023-10-25 13-26-06](https://github.com/mplp/docassemble-mlhframework/assets/6252212/b5bed263-e5a0-4f53-8214-758798a850a8)

**Comment by ekressmiller** [comment]
sounds good!
