### ISSUE TITLE
MLH_esign setting to "False" instead of asking the e-sign question.

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#30]
In the simple motion tool, I tried to switch out the signature screen to use the MLH_esign standard screen instead.  However, the motion interview skips the MLH_esign screen. 

The JSON file shows:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/f8760d87-59b2-42df-801a-839e0fab3f76)

I'm wondering if it's pulling from the code block at the top of the framework (which sets this False by default) before it gets to the question block? But I thought the normal rule was that Docassemble reads bottom to top.

**Comment by ekressmiller** [comment]
I figured this out. It was because I had not set "MLH_case_type_language" to anything (in this case to empty). The program needed that value for the template to ask MLH_esign. 

It's interesting to me that the program did not simply pull in the empty default value for MLH_case_type_language from the framework though.  

I'm closing this, but if anyone has thoughts about why the empty default value wasn't pulled in from the framework, I'd be interested!

**Comment by normon66** [comment]
The code block below is from the current framework yml. If you didn't have `MLH_case_type_language` defined somewhere in your yml, then yes - this should have been executed. 

`MLH_case_type_language` is only used in collapsible templates, never right in the `question` or `subquestion` text. It's unlikely, but could there be a bug where docassemble doesn't cascade down to templates? 

@ekressmiller 

```
---
code: |
  # This block contains MLH Organization-level variables that will vary from tool to tool.
  # These are the organization defaults.
  # Copy this block to an individual interview yml file and override as needed. 
  github_repo_name = "docassemble-General"  # default github repo
  MLH_instructions_included = False  # are instructions generated with the form(s)/letter(s)?
  MLH_court_forms = True             # Does this create forms to be filed with the court?
  MLH_esign_supported = True         # Are electronic signatures supported?
  MLH_esign = False                  # Add electronic signature?
  MLH_case_type_language = ""        # for e-filing help
  MLH_form_type = "form(s)"          # form / forms / letter (for use in intro/outro pages)
  MLH_time_min = 10
  MLH_time_max = 45
```

**Comment by ekressmiller** [comment]
Oh yeah, that's an interesting point.

**Comment by ekressmiller** [comment]
Changed my mind and reopening this because I'd love to know if @BryceStevenWilley has thoughts when he's back.

**Comment by normon66** [comment]
> The code block below is from the current framework yml. If you didn't have `MLH_case_type_language` defined somewhere in your yml, then yes - this should have been executed.
> 
> `MLH_case_type_language` is only used in collapsible templates, never right in the `question` or `subquestion` text. It's unlikely, but could there be a bug where docassemble doesn't cascade down to templates?
> 
> @ekressmiller
> 
> ```
> ---
> code: |
>   # This block contains MLH Organization-level variables that will vary from tool to tool.
>   # These are the organization defaults.
>   # Copy this block to an individual interview yml file and override as needed. 
>   github_repo_name = "docassemble-General"  # default github repo
>   MLH_instructions_included = False  # are instructions generated with the form(s)/letter(s)?
>   MLH_court_forms = True             # Does this create forms to be filed with the court?
>   MLH_esign_supported = True         # Are electronic signatures supported?
>   MLH_esign = False                  # Add electronic signature?
>   MLH_case_type_language = ""        # for e-filing help
>   MLH_form_type = "form(s)"          # form / forms / letter (for use in intro/outro pages)
>   MLH_time_min = 10
>   MLH_time_max = 45
> ```

Out of curiosity, I tested this out my unlikely hypothesis. I created a new page in my interview with a collapsible template. Within that template I made a reference to `MLH_case_type_language`, which I did **not** define in the interview yml file. Turns out that docassemble _did_ cascade down to retrieve the value of `MLH_case_type_language` from a temporary framework package that I created.

**Comment by BryceStevenWilley** [comment]
> It's interesting to me that the program did not simply pull in the empty default value for `MLH_case_type_language` from the framework though.

I think it's because to set that default value, it needs to execute the entire code block, not just one line from it. It's a little annoying, but the workaround is to split up each of those lines into individual code blocks. My rule of thumb is to avoid unexpected happenings, anytime you override one value of a variable in a code block, you likely need to override all of them. So IMO it makes sense to keep `MLH_time_min` and `MLH_time_max` in the same code block. I'll make a quick change that should prevent things like this from happening in the future.

**Comment by ekressmiller** [comment]
I hadn't realized that about how code blocks worked, thanks Bryce!

**Comment by normon66** [comment]
Oi. That's really annoying but really good to know. Thanks Bryce!
