### ISSUE TITLE
Change "thank you"

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#43]

**Comment by BryceStevenWilley** [comment]
Is this specifically on the feedback form page? https://github.com/mplp/docassemble-mlhframework/blob/a21fa4e5febc5bda32753435ff6a71de9a4b5a8d/docassemble/mlhframework/data/questions/mlh_feedback.yml#L101

I can't see anywhere else we use that phrase in this repo, unless you wanted to change it in all of our repos.

**Comment by ekressmiller** [comment]
This was me accidentally leaving the screen before I finished entering this.  Didn't realize it actually created anything. I created another issue with the complete idea on it. sorry for the confusion!
