### ISSUE TITLE
prod server feedback form tweaks

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#44]
1.
This page is great for dev but I think it needs to be simplified for prod.
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/bdf510e8-e8ba-43bf-bb7f-9d33f90a04a1)

2.
We need to update these links to MLH links
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/3ac55500-c44a-435b-9195-c1ae49b4b1f9)

**Comment by ekressmiller** [comment]
@normon66 I saw you assigned yourself on this so I won't start fiddling with it. I'm also happy to work on it if that makes sense though!  Below are what I'm kind of thinking, but very open to your take.

I'm imagining for # 1 for prod maybe we just need the first paragraph:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/e855e5b9-7ea6-4ada-8833-9fc5d2c83a09)
And we could potentially include the "more help" links (from # 2) here too, in case they're giving feedback about being stuck.  

For # 2 I'm imagining we would delete the "We are sorry . . . " line. And the remaining line could be "If you need more help, tap the links below."

- For Michigan legal information, [go to Michigan Legal Help](https://michiganlegalhelp.org/explore-legal-resources).  
- To chat with someone or send an email about your issue, [go to LiveHelp](https://michiganlegalhelp.org/livehelp).
- For information about free legal help or hiring a lawyer, [use the Guide to Legal Help](https://michiganlegalhelp.org/guide-to-legal-help).

**Comment by normon66** [comment]
@ekressmiller - I was thinking the same thing regarding the first paragraph. I only assigned myself since I had done the initial little lift on this, but go ahead and jump in if you'd like, as I won't have time right away to get to it. Thanks!
