### ISSUE TITLE
Adjust styling for 2nd-level headers

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#53]
As I understand it, if we want to use text enhancements to delineate headings, we should also apply header tags so screen readers can access the information in a similar way. It looks like the "Questions" are tagged as H1 (but "class" set to h3). When I set the headings within my subquestion to H2, they come out bigger than the question. Need to adjust them to be smaller than H1. Could probably even be normal font size but bold?

Appearance on screen of H1 question and H2 subheadings (in the subquestion)
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/7cf2ca91-f4a7-4c9d-b679-c087f987fcc6)

Inspect info for Question:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/c93fc359-21a0-45ff-99b9-28f8367a9f8d)

**Comment by BryceStevenWilley** [comment]
Yep, unfortunately it's a known issue. The solution is to manually set the header class: https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/coding_style_guide/accessibility#header-sizes.

I might be able to change our styles so all of the header sizes are one size smaller than the currently are, if that's doable I'll make the change.

**Comment by BryceStevenWilley** [comment]
I've got two different choices that could work pretty well here:

* we make all of the headers the same size or smaller than the title header, and make the slightly bolder to distinguish them from paragraph text a bit more (it's hard to tell the difference between an h4 or h5 and paragraph text).
   
   ![Screenshot from 2023-12-22 16-43-31](https://github.com/mplp/docassemble-mlhframework/assets/6252212/30966bfa-b33e-47bf-969d-24fa24d21686)
* we force the h1 to be the normal size of an h1. Note that this doesn't really change the size of the headers on mobile, there they intelligently scale to not take up the whole screen (they are a bit hard to distinguish from each other there, but they are still clearly distinguished from paragraph text).
  
  ![Screenshot from 2023-12-22 16-54-42](https://github.com/mplp/docassemble-mlhframework/assets/6252212/f951bc2c-9501-43dc-813c-ad7e10f30054)

  


For comparison, this is what that screen looks like now:

![Screenshot from 2023-12-22 16-43-43](https://github.com/mplp/docassemble-mlhframework/assets/6252212/283e1aeb-0ded-41cc-9ea9-684ffc8424fd)

**Comment by ekressmiller** [comment]
Thanks Bryce!  For Choice 1, I'd prefer making H2s a little smaller than H1. I think H2s will be the most fine-grained subheading we use in most cases so making that distinction feels useful.  For Choice 2, I think I slightly prefer the "larger and normal weight" option.  Feels slightly easier on the eyes.
