### ISSUE TITLE
Shrink the Nav bar content on mobile

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#57]
Things get pretty cramped, but we don't want the bar to double over

Also do this for the User Feedback screen (`User Feedbac`) (?disco=AAABDEjMkwY)

disco=AAABDEjMkvI

**Comment by BryceStevenWilley** [comment]
As expected, this gets a little difficult and we have to start making tradeoffs. The best I can come up with at the moment is:

* smaller text (going back to Assembly Line default)
* a smaller logo and menu button
* capping the title to a percentage of the screen width, so it doesn't push the menu button to another line.

The biggest downsides to these choices are:

* the text is pretty small. I'd like to get rid of the org title, but I'm not sure I can with just CSS, or with docassemble
* even making everything smaller, you can only fit about 30 characters (plus or minus a few) before it clips out. The landlord short title is still too long. It only clips on small screens like the iPhone 5 though; iPhone 6/7/8, Nexus 6p, and Pixel 2 are all good with the current title length. So maybe we just front-load the semantic meaning at the front of the title, knowing that some people won't be able to see past 30 characters.

![Screenshot from 2023-12-22 12-42-42](https://github.com/mplp/docassemble-mlhframework/assets/6252212/0557adf7-814b-4657-ae13-cc981db499a1)

**Comment by normon66** [comment]
I think that will work fine. For this one, I can change the `short title` to "Security Deposit Letter"

**Comment by ekressmiller** [comment]
I think that makes sense as a place to land for now. I agree I wish we could remove the org title. Maybe something to ask about at a Suffolk meeting?

**Comment by BryceStevenWilley** [comment]
> I agree I wish we could remove the org title. Maybe something to ask about at a Suffolk meeting?

I looked into it a little more and it is a docassemble thing! Assembly Line just defines `logo` and `short logo` to the same thing, but we can override the short logo. It looks okay, I don't want to make the text much bigger so users can see enough of it. 

![Screenshot from 2024-01-02 14-46-34](https://github.com/mplp/docassemble-mlhframework/assets/6252212/eea2068c-8c5d-42a0-acbc-f09a5469bf78)

Also of note is that the short logo is used on any screen less than 1000 pixels, which includes iPads. Not ideal, but I think we want to optimize for mobile and desktop, not for tablet devices.

I'll push those changes and merge!
