### ISSUE TITLE
Downlod Document section excluded by screen reader?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#62]
Test in a few different browsers and OS's if possible. Likely an AL fix is needed.

Google doc comment link: ?disco=AAABDEjMkwc

**Comment by BryceStevenWilley** [comment]
I can't recreate this: both Chrome on Linux with Orca and Firefox on Android with Talkback work fine. Could be better, but nothing's being excluded. Should ask what "page reader" is, and see if I can reproduce it.

**Comment by ekressmiller** [comment]
I was thinking they meant RSS Voice

**Comment by ekressmiller** [comment]
Yeah just tested RSS Voice on my iphone and it skipped from "Edit Answers" to "Get a copy of the documents in email". So it never read the document names or view/download buttons.

**Comment by BryceStevenWilley** [comment]
Ah, gotcha.  I'll have to see if there's an upstream fix for that, docassemble handles it all internally.

**Comment by BryceStevenWilley** [comment]
Looking into it more, there are a lot of general issues with the screen reader that I won't have time to fix. For posterity:

* docassemble tries to be smart about what content is read out, and it skip over anything that's in a `div`, which includes the download section.
* it also reads parts of the page that are hidden, including the [in-interview feedback widget](https://github.com/SuffolkLITLab/docassemble-GithubFeedbackForm/blob/main/docassemble/GithubFeedbackForm/data/questions/embedded_review.yml), because it's only looking for `aria-hidden` and not `hidden` or `display: none`, all of which should semantically hide content.

I see the idea, but it's running into the fact that you'd have to be a browser to know what parts of the page are shown to users. The few tweaks upstream I've tried to make here don't help, but for this specific issue, we can wrap the given lines in our interviews in paragraph HTML tags:

```html
<p>
${ al_user_bundle.download_list_html() }
</p>
```.

I'll leave this issue open until I have PRs out to fix our existing interviews, and to adjust this in the Weaver to come out right.

**Comment by ekressmiller** [comment]
Thanks Bryce!

**Comment by BryceStevenWilley** [comment]
PRs all made, going to close this now.

**Comment by BryceStevenWilley** [comment]
Reopening since Quinten rightfully noted that this workaround is invalid HTML and could cause that page to look and behave differently between different browsers, something we do want to avoid. We can discuss more tomorrow, but IMO, this is making me heavily lean towards turning off voice RSS on our servers.

**Comment by ekressmiller** [comment]
Emily to discuss with MLH team the jankyness -- usefulness tradeoff of Voice RSS, and decide whether to turn on or off.

**Comment by BryceStevenWilley** [comment]
I went ahead and turned off VoiceRSS on our 2 servers. (just changed `voicerss: `, to `enabled: False` in the config). https://github.com/SuffolkLITLab/docassemble-AssemblyLine/discussions/812 is the Assembly Line discussion on how to proceed with improving the VoiceRSS feature upstream / in Assembly Line.|

I'm going to re-close this again, as if / when there are upstream updates, I'm sure Assembly Line will talk about them with users.
