### ISSUE TITLE
Consider styling our undo button more like a button?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#63]
Try it out and see how it looks for a bit. Would make a stronger boundary between the screen content and footer / under stuff.

Google doc comment link: ?disco=AAABDEjMkwk

**Comment by BryceStevenWilley** [comment]
Looks okay? I'll keep using it and we'll see what we think. It's an easy change.

![Screenshot from 2023-12-22 16-18-09](https://github.com/mplp/docassemble-mlhframework/assets/6252212/ce5e1220-20e9-4553-a1ed-7a07a62b8a46)

**Comment by normon66** [comment]
I like it. Helps frame in the question from the below text, as well.

**Comment by ekressmiller** [comment]
I really like it!
