### ISSUE TITLE
back button label

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#7]
Hey Brett, I think it may be worth going with "Undo" as the default for the back button label since it signals to users that if they go back they are going to _lose_ the information they see on the current screen. I know Suffolk put a lot of thought into that.

**Comment by BryceStevenWilley** [comment]
Also relevant here: if we refer to the name of the "undo" button in the text, we can make sure it matches what the button actually says by using `all_variables(special='title').get("back button label")`. I'd need to test it, but I think that should fix it

**Comment by normon66** [comment]
Closed by commit 148a45b867ee2a2165b91edc3df2a648f56d341b

This had already been implemented in framework, so I simply changed the label:
![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/d2043791-d04f-494e-b91f-d87f0b10fe6b)
