### ISSUE TITLE
Remove "Share my answers with administrator" checkbox

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#74]
Per 12/21/23 call with team, remove "Share my answers with administrator" checkbox on User Feedback page

https://docs.google.com/document/d/1m5Fd0qP425uvJq8m4Zkfm_Ki9lVXuwF5t4ISUreTvlk/edit#bookmark=id.8ip60dxiraw4

**Comment by normon66** [comment]
It looks like we'd actually be able to hide this (and related messages) easily by changing the `feedback session linking` config item to False. See [AL documentation here](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/github_feedback#configuration). 

However, there may be instances where we DO want to have that an option, even though changing it would be a quick and easy fix for this particular issue. 

See [relevant line in AL's feedback yml](https://github.com/SuffolkLITLab/docassemble-GithubFeedbackForm/blob/db038e5a0211212442d5184dd1feeac7cea525b0/docassemble/GithubFeedbackForm/data/questions/feedback.yml#L56C13-L56C14).

**Comment by ekressmiller** [comment]
"feedback session linking" has been set to False on prod server. 

For now, we don’t think this option adds much, and is confusing for users. Consider adding later if AL improves the functionality to better connect the report to a specific vars file or a session on the backend feedback browsing tool.
