### ISSUE TITLE
Remove "button" from back/undo in question text

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#75]
Per 12/21/23 call with team, remove "button" after MLH_back_button_label

https://docs.google.com/document/d/1m5Fd0qP425uvJq8m4Zkfm_Ki9lVXuwF5t4ISUreTvlk/edit#bookmark=id.rns0kyldky9g

**Comment by BryceStevenWilley** [comment]
Related to #63; if we want to make it look more like a button, we probably should keep the text about it being a button.

**Comment by BryceStevenWilley** [comment]
Since we seemed to like actually changing Undo to a button in #63, I'm gonna close this issue and the comment in the doc, which should be accurate now that it's a button.
