### ISSUE TITLE
help text readability

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#82]
With new update to the collapsible template styling, it looks beautiful in Firefox:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/e4404305-8fb0-4b87-a036-6686e5c2f923)

But kind of hard to read in Chrome:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/680c943b-68c3-404e-b5a0-6b9f4e38517e)

I may not have noticed the green dashes being a problem in Chrome before because we haven't used too many pop-up definitions yet and because those tend to be shorter, just a single word or two instead of a whole sentence.

**Comment by ekressmiller** [comment]
Can change to dotted instead of dashed, but it still feels hard to read in Chrome:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/c3fc8caf-790c-433b-9f98-5119ad61e5d0)

**Comment by nonprofittechy** [comment]
Looks like something is different with the line height in Chrome vs Firefox. There may also be different defaults for the dash length on the 2 platforms.

**Comment by ekressmiller** [comment]
Thanks!

**Comment by ekressmiller** [comment]
Bryce suggested:
