### ISSUE TITLE
Improve titles for feedback form issues

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#84]
Amy noted she had trouble locating feedback she gave previously because the auto-generated titles are not very descriptive.  

Would be nice if the expert reviewer's feedback could have clearer titles.

Possibilities to look into:

- Developers manually rename issues to be more descriptive (with or without a suggestion from reviewer)
- Can we program in a field to the feedback form for the reviewer to name the issue?

**Comment by BryceStevenWilley** [comment]
Devs should definitely rename issues to be more descriptive, apologies, I should have done that when I triaged those issues.

It's probably a possibility to improve the issue title: https://github.com/SuffolkLITLab/docassemble-GithubFeedbackForm/blob/b8ade2b77efe21672ee9aaa3980e0759379f31f5/docassemble/GithubFeedbackForm/data/questions/feedback.yml#L277-L283 is the code that makes the title. I like the idea of reviews renaming their issues, anything we do automatically would still likely confuse people when they go to try to find it.

**Comment by ekressmiller** [comment]
Will bring this back up at a team meeting to see which way we want to go with this.

**Comment by ekressmiller** [comment]
For now, devs will rename, can consider building way for reviewers to name in future.
