### ISSUE TITLE
Standardize image and name at upper left.

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#9]
I recently added a logo and the AL org title to the framework so now within an interview that incorporates the framework, the upper left looks like this:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/ac1219e5-b188-4512-bba3-49f756d17a9b)
and the link goes to our homepage.

On the My Interviews page, it looks like this, and the link is to courtformsonline.org (because of course it doesn't pull in info from the framework). I tried setting a brandname in the config, but it didn't seem to have an effect.
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/721590c2-5f55-4c6b-a439-1dec59861aee)
How do we set the image, name and link that appear on the My Interviews page?

**Comment by BryceStevenWilley** [comment]
The way to do that is to make a "wrapper" interview in the framework, where you make a `*.yml` file that does little else other than include `docassemble.AssemblyLine:interview_list.yml` and `mlh_interview_framework.yml`, to override any of the default logos and such.

I'll make that now, and merge it just to get it in.
