### ISSUE TITLE
Standardize Review screen look and feel

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#91]
Per 2/29/24 call with team, this issue is being opened as a placeholder discuss/determine a consistent look and feel of the Review screen.

For example:
* Should there be section headings, and if so, what size/style?
* Use horizontal rules between sections?
* Implement collapsible sections on longer tools?
* Should prompts have a trailing semicolon?

After discussion, we decided to let each developer run with their own methods and revisit this in the future after taking numerous unique variations into consideration. 

![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/783a803e-7bcd-4e55-b7af-60de97cc5e80)

**Comment by normon66** [comment]
With implementation of @ekressmiller's fantastic accordion method (PR #126), I think it's safe to close this. @ekressmiller - thuoghts?

**Comment by ekressmiller** [comment]
I think that makes sense, thanks @normon66!
